apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librespeed
  template:
    metadata:
      labels:
        app: librespeed
    spec:
      containers:
        - name: librespeed
          image: lscr.io/linuxserver/librespeed
          ports:
            - containerPort: 80
          env:
            - name: PUID
              value: "1000" # Replace with your PUID
            - name: PGID
              value: "1000" # Replace with your PGID
            - name: TZ
              value: "America/New_York" # Replace with your timezone
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - name: config
              mountPath: /config
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: librespeed-pvc
